pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./2_2-activating-a-mistika-vr-li.html","Installation and configuration &#62; License management","Apart from this manual, here you can find up to date instructions for licensing and trouble shooting:  https://support.sgo.es/a/solutions/art...",""],
["./2_2-activating-a-mistika-vr-li_2.html","Installation and configuration &#62; License management &#62; Activating a Mistika Workflows license with Internet Connection (2)","Activation codes and license management are processed either by means of the SGO License Activation Tool or directly in your SGO web account (SGO ...",""],
["./2_3-activating-a-mistika-vr-li.html","Installation and configuration &#62; License management &#62; Activating a Mistika Wrofklows license without Internet Connection","Users who need to activate a Mistika Technology products on a computer not connected to the internet, can follow these steps:",""],
["./2_4-how-to-configure-a-floatin.html","Installation and configuration &#62; License management &#62; How to configure a floating license in Mistika Workflows","To configure one system to read the license from a remote License Server, follow this simple steps: ",""],
["./2_5-active-licenses-r-.html","Installation and configuration &#62; License management &#62; Managing active licenses ","All active licenses linked to your account can be found in the Advanced mode of the SGO License Activation Tool. This allows the activation and de...",""],
["./3_-first-launch-of-mistika-vr.html","Installation and configuration &#62; License management &#62; First launch of Mistika Workflows","On the first launch of Mistika Workflows, an SGO Software License Agreement prompt will appear. To read the whole license agreement, use the scrol...",""],
["./4_-mistika-wf-interface.html","Mistika Workflows Interface","The Mistika Workflows interface Navigation: No topics above this level The Mistika Workflows interface ",""],
["./acesgamutcompress.html","Nodes &#62; Tasks &#62; ACES Gamut Compress","Purpose  Applies an ACES Gamut Compress, or the reverse transformation (Inverse property) Inputs  Input_1:  Any media files.  ...",""],
["./acesinvodt.html","Nodes &#62; Tasks &#62; ACES InvODT","Purpose  Applies an inverse color transformation, according to ACES-ODT standards. This node is similar to the ACES ODT node, but provides sp...",""],
["./acesodt.html","Nodes &#62; Tasks &#62; ACES ODT","Purpose  Applies an ACES color transformation, typically when from camera RAW formats to other color spaces, according to ACES-ODT standard. ...",""],
["./adiv1.html","Nodes &#62; Tasks &#62; ADI v1","Purpose  This node creates an XML file in ADI v1.1 / Cablelabs 1.1 format (or ADIv3 / Cablelabs 3.0 in the case of SkyADI).  The  A...",""],
["./aftereffectsfile.html","Nodes &#62; Input &#62; After Effects File","Purpose  This node imports an After Effects .aep file and overrides selected parameter values with the metadata received trough the override ...",""],
["./aftereffectsrender.html","Nodes &#62; Tasks &#62; After Effects Render","Purpose  This node receives.aep files (After Effects Projects) and it uses the After Effects command line renderer to render them, and finall...",""],
["./amberscript.html","Nodes &#62; Tasks &#62; Amberscript","Purpose  This node provides integration with Amberscript , an AI-based cloud service that can transform audio and video into text transcripti...",""],
["./arrifile.html","Nodes &#62; Input &#62; Arri File","Purpose  This node will load ARRI RAW files and set their properties before passing them to other nodes. Supports .mxf, .ari, and .arx files....",""],
["./asperaclient.html","Nodes &#62; Output &#62; Aspera Client","Purpose  File transfer through the Aspera platform. This node allows you to upload or download files (depending if you use the Input or Outpu...",""],
["./asperaclient_out.html","Nodes &#62; Input &#62; Aspera Client","Purpose  File transfer through the Aspera platform. This node allows you to upload or download files (depending if you use the Input or Outpu...",""],
["./audiorouter.html","Nodes &#62; Tasks &#62; Audio Router","Purpose  To select and recombine audio channels of the input media, mainly to prepare audio tracks for transcoder nodes downstream . Note: Th...",""],
["./auto-naming-tools.html","Mistika Workflows Interface &#62; Name convention for file naming and numbering","Mistika Workflows provides an auto-naming mechanism to ensure file naming coherence and automatic naming. This system also permits to extract meta...",""],
["./autotrigger.html","Nodes &#62; Input &#62; Auto Trigger","Purpose  This node forces to execute the workflow periodically, every time interval It does not need to be connected, just the presence of th...",""],
["./avi.html","Nodes &#62; Tasks &#62; AVI","Purpose  To create AVI mp4 files  Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The audio tracks to be...",""],
["./avidv.html","Nodes &#62; Tasks &#62; Avi DV","Purpose  Create an .avi file from the content connected to the input.  Inputs  AV In: The image track to be encoded.  Ext. Aud...",""],
["./azurein.html","Nodes &#62; Input &#62; AzureIn","Purpose  This node allows you to download files from Azure Storage.   Outputs   Out: To pass downloaded files to other nodes. &#38;nbsp...",""],
["./azureout.html","Nodes &#62; Output &#62; AzureOut","Purpose  This node allows you to upload files to Azure Storage.  Inputs  in: Files to be uploaded.  Outputs   Out: To pas...",""],
["./bmp.html","Nodes &#62; Tasks &#62; Bmp","Purpose  To create a .BMP file or a .BMP enumerated sequence of files. These .BMP files can include alpha channel or not depending on the sel...",""],
["./brawfile.html","Nodes &#62; Input &#62; BRaw File","Purpose  This node will load BRAW files and set their properties before passing them to other nodes.  Outputs  AV Out: The BRAW fil...",""],
["./canonfile.html","Nodes &#62; Input &#62; Canon File","Purpose  This node will load Canon RAW files and set their properties before passing them to other nodes. Two nodes are provided (Canon File ...",""],
["./canonmovie.html","Nodes &#62; Input &#62; Canon Movie","Purpose  This node will load Canon RAW files and set their properties before passing them to other nodes. Two nodes are provided (Canon File ...",""],
["./cdl.html","Nodes &#62; Tasks &#62; CDL","Purpose  This node allows to associate CDL metadata (basic color grading parameters) based on the ASC-CDL standard (Offset, Power, Slope and ...",""],
["./change8kp2metadata.html","Nodes &#62; Tasks &#62; Change8KP2metadata","Purpose  This node allows to change the metadata of a Panasonic 8KP2 pack input node. Outputs  AV Out: A sequence of media files.  ...",""],
["./changecurvesdata.html","Nodes &#62; Tasks &#62; changeCurvesData","Purpose  This node that can get a Mistika script file  (typically coming from other Mistika products) and overwrite the value of any eff...",""],
["./changenameconvention.html","Nodes &#62; Tasks &#62; Change Name Convention","Purpose  This node allows to define the Name Convention that needs to be used in order to interpret the file names of the input files.  ...",""],
["./changeresolution.html","Nodes &#62; Tasks &#62; changeResolution","Purpose  This node allows to redefine the render resolution of the workflow, either by a scale factor (percentage) or in absolute number of p...",""],
["./chapter-2.html","Installation and configuration","First, create your account at SGO (remember to confirm your account by clicking the link you will receive in your email).",""],
["./checksum.html","Nodes &#62; Tasks &#62; Checksum","Purpose  Given an input file this node calculates its CRC using the specified algorithm. A checksum file is a file in the same folder and wit...",""],
["./classifybyage.html","Nodes &#62; Tasks &#62; classifyByAge","Purpose  This python node filters the input media by younger or older than a time interval given by user (compared with the system clock) &#38;nb...",""],
["./classifybyaspectratio.html","Nodes &#62; Tasks &#62; classifyByAspectRatio","Purpose  This python node will classify the input media by its aspect ratio, sending different ranges of aspect ratios trough different conne...",""],
["./classifybyextension.html","Nodes &#62; Tasks &#62; classifyByExtension","Purpose  This python node filters the input media by its extension. In this way, you can route different types of media files through differe...",""],
["./classifybymetadata.html","Nodes &#62; Tasks &#62; classifyByMetadata","Purpose  This node classify the input files by the designed metadata token. You can put the metadata token in the Data Type property, and its...",""],
["./classifybysize.html","Nodes &#62; Tasks &#62; classifyBySize","Purpose  This python node will classify the input media by its file size, sending different ranges of sizes trough different connectors. You ...",""],
["./classifybytokens.html","Nodes &#62; Tasks &#62; classifyByTokens","Purpose  Given input files and a separator character to split the file name into meaningful tokens,  this node will classify the input f...",""],
["./common-parameters.html","Nodes &#62; Standard properties","General properties  The properties in this section are available to multiple nodes, and this section is to have them documented in just one p...",""],
["./comp3d.html","Nodes &#62; Tasks &#62; Comp3D","Purpose  To compose any number of input layers over a background clip, based on the alpha channel of each layer. Note: This node is based on ...",""],
["./concatxls.html","Nodes &#62; Tasks &#62; ConcatXLS","Purpose  This node permits to join several .XLS spreadsheet files into a single one, which is a common need when trying to automate workflows...",""],
["./conformfilter.html","Nodes &#62; Tasks &#62; ConformFilter","Purpose  To filter the input media files by selecting the ones that are mentioned (or not mentioned) in an EDL, XML, or AAF file. The node wi...",""],
["./contextual-menus.html","Main menu &#62; Contextual menus","By right clicking with your mouse or pen you will find the following contextual menus in certain interface tabs. ",""],
["./contextual-menus2.html","Main menu &#62; Nodes (menu) &#62; Tasks","Nodes that perform any kind of actions with files (files that have been already imported with Input nodes).  That includes a wide variety of ...",""],
["./copy.html","Nodes &#62; Tasks &#62; Copy","Purpose  A speed optimized node to copy files.  This node is media content aware, as most other nodes are. That means that all the relat...",""],
["./copyto8kp2cards.html","Nodes &#62; Tasks &#62; CopyTo8KP2cards","Purpose  This node allows to copy the content of the input node into five P2 cards by following the Panasonic 8KP2 structure.  Inputs &#38;n...",""],
["./creating-a-project.html","Mistika Workflows Interface &#62; Connecting the nodes","Mistika Workflows provides a node based interface, including three types of nodes:",""],
["./crop.html","Nodes &#62; Tasks &#62; Crop","Purpose  To crop the input media while creating black area (or solid color) around the cropped area. Permits cropping all channels  (RGB...",""],
["./csvtodfilt.html","Nodes &#62; Tasks &#62; CSVtoDFILT","Purpose  A powerful Python example, it shows how to modify the text information inside the \"Watermark\" display filter by getting it...",""],
["./csvtoupmdata.html","Nodes &#62; Tasks &#62; CSV to UP metadata","Purpose  This node reads user custom metadata from a .csv file (basically a text file with delimiters representing a simple table or spreadsh...",""],
["./dcppack.html","Nodes &#62; Input &#62; DCP pack","Purpose  The DCPfolder node permits to load (read) a non encrypted digital cinema package (DCP) video file.  Standard properties Object ...",""],
["./denoise.html","Nodes &#62; Tasks &#62; Denoise","Purpose  Denoise input images, either by using optical flow techniques (tracking individual image features over the time) or by using spatial...",""],
["./digixml.html","Nodes &#62; Tasks &#62; DigiXML","Purpose  This node creates .xml delivery packages to the specifications of the company \"Digi\". The delivery package is made of an X...",""],
["./dngfile.html","Nodes &#62; Input &#62; DNG File","Purpose  This node will load DNG files and set their properties before passing them to other nodes.  Outputs  AV Out: A .DNG file o...",""],
["./dnxhd.html","Nodes &#62; Tasks &#62; DNxHD","Purpose  To create a .mxf DNxHD file.  Inputs  AV In: Input media files to be transcoded.  Ext. Audio (Optional): The audio tr...",""],
["./dnxhdopatom.html","Nodes &#62; Tasks &#62; DNxHDOpAtom","Purpose  To create a .mxf DNxHDOp-atom file.  Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The audio ...",""],
["./dnxhr.html","Nodes &#62; Tasks &#62; DNxHR","Purpose  To create a .mxf DNxHR file.  Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The audio tracks ...",""],
["./dolbyvision.html","Nodes &#62; Tasks &#62; Dolby Vision","Purpose  To apply Dolby Vision tone mapping.  This node gets a master media file containing an HDR master (in any supported image format...",""],
["./dpx.html","Nodes &#62; Tasks &#62; DPX","Purpose  To create a .dpx (Digital Picture Exchange) file or a .dpx enumerated sequence of files. These .dpx files can include alpha channel ...",""],
["./dropboxin.html","Nodes &#62; Input &#62; dropboxIn","Purpose  File transfer through the Dropbox platform. This node allows you to download files. A Dropbox Out node is also available for the cas...",""],
["./dropboxout.html","Nodes &#62; Output &#62; dropboxOut","Purpose  This node allows you to upload files to your Dropbox cloud account (a Dropbox In node is also available for the case of downloads). ...",""],
["./edit-window.html","Main menu &#62; Edit ","The edit menu contains actions for the selected nodes: Copy, Cut, Paste, and Delete.",""],
["./editmetadata.html","Nodes &#62; Tasks &#62; EditMetadata","Purpose  Permits adding or changing user metadata associated with the input media, including technical data about camera recording settings, ...",""],
["./editready.html","Nodes &#62; Tasks &#62; EditReady","Purpose  This node integrates the Hedge Video EditReady Server application into Mistika Workflows so that transcoding jobs can be done by usi...",""],
["./edleditchanges.html","Nodes &#62; Tasks &#62; EDL Edit Changes","Purpose  This node uses two EDL files as input and checks each event to see if there has been any editing changes between them.  Based o...",""],
["./edlreference.html","Nodes &#62; Tasks &#62; EDL Reference","Purpose  The main task of this node is to automate the process of providing a reference movie file for each VFX shot given in a VFX pull, whe...",""],
["./edltocc.html","Nodes &#62; Tasks &#62; EDL to CC","Purpose  This node gets one or more EDL files (with .edl extension), extracts the CDL information for each shot and creates a .cc file for ea...",""],
["./edltomarkers.html","Nodes &#62; Tasks &#62; EDL to Markers","Purpose  This node takes one or more EDL files (files with the .edl extension) and creates new EDL files for each of them. These new EDL file...",""],
["./exr.html","Nodes &#62; Tasks &#62; Exr","Purpose  To create a .EXR file or an .EXR enumerated sequence of files. In the particular case that the source files were also .exr,  th...",""],
["./exrfile.html","Nodes &#62; Input &#62; Exr File","Purpose  The EXR File input node permits to load a sequence of .exr files with correlative number. Most common exr formats are supported, wit...",""],
["./externalbinary.html","Nodes &#62; Tasks &#62; External Binary","Purpose  Execute a external binary from another program, passing the incoming file to it and waiting for it to complete processing it.  ...",""],
["./extractaudiochannels.html","Nodes &#62; Tasks &#62; Extract Audio Channels","Purpose  To extract audio channels of the input media providing separate outputs for each one, also providing meaningful metadata downstream ...",""],
["./failedups.html","Nodes &#62; Input &#62; Failed UPs","Purpose  This node permits to create an error control workflow. If this node is present in a workflow tab, whenever a node fails at execution...",""],
["./ffmpeg.html","Nodes &#62; Tasks &#62; ffmpeg","Purpose  To provide a Python example about how to integrate external CLI programs with Mistika Workflows, by using the ffmpeg CLI as an examp...",""],
["./file-menu.html","Main menu &#62; File Menu","The file menu contains the following features:     - New: it will create a new Mistika Workflows project ( .mwf file). A workflow projec...",""],
["./file.html","Nodes &#62; Input &#62; File","Purpose  This node allows you to load a new file of any type to your workflow before passing it to other nodes.  For example, to load me...",""],
["./filemail.html","Nodes &#62; Output &#62; Filemail","Purpose  Send files via the Filemail platform.  Inputs  in: Files to upload.  A first input connector is provided, but you can...",""],
["./fixp2serial.html","Nodes &#62; Tasks &#62; Fix P2 Serial","Purpose  This node patch connected P2 cards to put its corresponding serial number in all the XML files found inside. Inputs  Input: The...",""],
["./folder.html","Nodes &#62; Input &#62; Folder","Purpose  Use this node to import all the files from a folder and pass them to other nodes. Support recursive sub-directories.  The Folde...",""],
["./frameio.html","Nodes &#62; Output &#62; FrameIO","Purpose  Upload content to a Frame.io platform account. Note: To access Frame.io you need to have created an account on this platform. In add...",""],
["./framing.html","Nodes &#62; Tasks &#62; Framing","Purpose  Apply framing operations to input media, including rescaling, cropping, offset, mirror, roll, and rotate. This node does not create ...",""],
["./ftp.html","Nodes &#62; Input &#62; FTP","Purpose  This node allows you to upload or download files on FTP servers (depending if you use the Input or Output node versions).  Inpu...",""],
["./ftp_output.html","Nodes &#62; Output &#62; FTP","Purpose  This node allows you to upload or download files via FTP protocol (depending if you use the Input or Output node versions).  In...",""],
["./gif.html","Nodes &#62; Tasks &#62; Gif","Purpose  To create a .Gif file or a .Gif enumerated sequence of files. These .Gif files can include alpha channel or not depending on the sel...",""],
["./googledriveout.html","Nodes &#62; Output &#62; Google Drive Out","Purpose  This node upload incoming files to a Google Drive folder Before you can use this node you will need to get some credentials from Goo...",""],
["./googledriveout_2.html","Nodes &#62; Input &#62; Google Drive In","Purpose  This node download a Google Drive folder. Watch a video tutorial here: https://www.youtube.com/watch?v=WtHOokfMVco Before you can us...",""],
["./h264.html","Nodes &#62; Tasks &#62; H264","Purpose  To create compressed media files using the H264 software based  encoder. This task node is slower and more limited than modern ...",""],
["./hardlink.html","Nodes &#62; Tasks &#62; Hard Link","Purpose  This node creates a hard link of the input files to the desired path destination.   This can be useful in certain situations wh...",""],
["./help.html","Main menu &#62; Help","Provide access to Mistika Workflows documentation, support resources and community forums.",""],
["./importmlnk.html","Nodes &#62; Input &#62; Import Mlnk","Purpose  When loading a media file into other Mistika applications for the first time, the media file is analyzed and a \".mlnk\" fil...",""],
["./input-nodes.html","Main menu &#62; Nodes (menu) &#62; Input","The Input nodes permit to import files into the workflow. We can distinguish these cases:",""],
["./input.html","Nodes &#62; Input","Input Navigation: Nodes Input ",""],
["./interface.html","Mistika Workflows Interface &#62; Interface panels","Every time you open Mistika Workflows an unnamed project is created with an empty Nodegraph. The user may start with that new project or open the ...",""],
["./introduction-to-python-scripti.html","Python scripting tools &#62; Introduction to python scripting tools","Introduction Mistika Workflows have integrated support for Python programming language (Currently Python 3.11). This language provides bidirection...",""],
["./introduction.html","Introduction","As part of its Multidimensional Workflow Concept, SGO has started to slice features and toolsets of its globally-acclaimed Hero Suite Mistika Ulti...",""],
["./j2k.html","Nodes &#62; Tasks &#62; J2k","Purpose  To create a .J2K file or a .J2K enumerated sequence of files  (JPEG2000).  These .J2K files can include alpha channel or n...",""],
["./j2ksequence.html","Nodes &#62; Input &#62; J2k Sequence","Purpose  This node will load J2K Sequences  (JPEG2000, typically used for DCP packaging) and set their properties before passing them to...",""],
["./join8kp2contents.html","Nodes &#62; Tasks &#62; Join8KP2contents","Purpose  Join different Panasonic 8KP2 packs into packs with specific size to copy into a P2 card. Inputs  P8: The Panasonic 8KP2 packs ...",""],
["./joinmovies.html","Nodes &#62; Tasks &#62; Join Movies","Purpose  To join different segments of the same media into one clip.  A common use is to join movie segments that were divided in multip...",""],
["./jpeg.html","Nodes &#62; Tasks &#62; Jpeg","Purpose  To create a .Jpg file or a .Jpg enumerated sequence of files. These .Jpg files can include alpha channel or not depending on the sel...",""],
["./leonardassist.html","Nodes &#62; Tasks &#62; Leonard Assist","Purpose  This node is part of the integration between Mistika Workflows and DaVinci Resolve. The Leonard Assist node runs in the Mistika Work...",""],
["./leonardassistforresolve.html","Leonard Assist for Resolve","Purpose  This node is part of the integration between Mistika Workflows and DaVinci Resolve. The Leonard Assist node runs in the Mistika Work...",""],
["./lut3d.html","Nodes &#62; Tasks &#62; LUT 3D","Purpose  To apply a LUT (1D LUT and/or a 3D LUT, or a shaper LUT)  to the incoming media.  The LUTs can either be generated in Mist...",""],
["./mail.html","Nodes &#62; Output &#62; Mail","Purpose  Send an email message using smpte protocol. Note: Depending on the mail server it may be necessary to make some specific adjustments...",""],
["./mail_2.html","Nodes &#62; Output &#62; Gmail","Purpose  Send an email message via Gmail service. Note: Gmail requires to add permissions to your account for sending messages in your name f...",""],
["./masv.html","Nodes &#62; Output &#62; MASV","Purpose  Upload content to a Massive.io platform account and generate the corresponding download links. Note: To access Massive.io you need t...",""],
["./mediamovie.html","Nodes &#62; Input &#62; Media Movie","Purpose  The MediaMovie node permits to load movie files that do not have its own specialized nodes.  Support generic containers such as...",""],
["./mediasequence.html","Nodes &#62; Input &#62; Media Sequence","Purpose  The Media Sequence node permits to load a sequence of files with correlative frame numbers. This node is indicated for enumerated im...",""],
["./metadatatocsv.html","Nodes &#62; Tasks &#62; Metadata To CSV","Purpose  This node takes input files from any other node, such a Folder node, and generates a .csv   file with several columns with meta...",""],
["./mistika-python-extension-libra.html","Python scripting tools &#62; Mistika Python extension library","The Python class library with all the Mistika Workflows structures is available at https://www.sgo.es/doc/python/. ",""],
["./mistika-wf-folder-structure.html","Installation and configuration &#62; Mistika Workflows folder structure","This is an introduction to the folder structure that Mistika Workflows will create in your computer. Only the relevant user folders are mentioned,...",""],
["./mistikajs.html","Nodes &#62; Tasks &#62; Mistika Js","Purpose  To create Mistika .js image files using Mistika own format. The Mistika .js is an image format optimized for full quality (uncompres...",""],
["./mistikamlnk.html","Nodes &#62; Tasks &#62; Mistika Mlnk","Purpose  When impòrting media files into other Mistika applications, the media files are analyzed and a \".mlnk\" file is created in ...",""],
["./mistikarender.html","Nodes &#62; Tasks &#62; Mistika Render","Purpose  The MistikaRender node permits to execute render processes for Mistika render jobs (.rnd script files), which can be created with ot...",""],
["./move.html","Nodes &#62; Tasks &#62; Move","Purpose  Use this node to move files. This node is media content aware, as most other nodes are. That means that all the related files belong...",""],
["./movistarvoditem.html","Nodes &#62; Tasks &#62; Movistar VOD item","Purpose  This node prepares a Movistar  VOD item (each item made of a video file and optionally one or more still images, alongside desc...",""],
["./movistarxmlv93.html","Nodes &#62; Tasks &#62; Movistar XML v9.3","Purpose  This node creates delivery packages to the specifications of Movistar  (which are based on their own XML specifications). &#38;nbsp...",""],
["./mp3.html","Nodes &#62; Tasks &#62; MP3","Purpose  The primary purpose is to extract input audio and export it to a .mp3 file. The input audio can be a movie file containing audio or ...",""],
["./mpeg.html","Nodes &#62; Tasks &#62; MPEG","Purpose  To create MPEG files  Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The audio tracks to be en...",""],
["./nctometadata.html","Nodes &#62; Tasks &#62; NC to metadata","Purpose  Name Convention to metadata. To extract metadata values from sub-strings of the paths and filenames of the input files, by matching ...",""],
["./nodes-panel.html","Main menu &#62; Nodes (menu)","There are three types of nodes:  Input, Task, and Output. This menu contains the same node as the Finder panel in the left side of the interf...",""],
["./nodes.html","Nodes","Preliminar Note: In the GUI (and in this documentation) you may find a same node mentioned with slightly different names: ",""],
["./nvidiah264.html","Nodes &#62; Tasks &#62; Nvidia H264","Purpose  To create .mp4 media files using the NVidia H264 encoder. This is a GPU hardware encoder, so this is much faster than software based...",""],
["./nvidiah265.html","Nodes &#62; Tasks &#62; Nvidia H265","Purpose  To create .mp4 media files using the NVidia H265 and NVidia H264 nvenc encoders. These are GPU hardware encoders, so they are much f...",""],
["./objectmatrixin.html","Nodes &#62; Input &#62; Object Matrix In","Purpose  These nodes allow to upload or download media files to Object Matrix cloud services.  Inputs (output nodes only)  in: This...",""],
["./objectmatrixout.html","Nodes &#62; Output &#62; Object Matrix Out","Purpose  These nodes allow to upload or download media files to Object Matrix cloud services.  Inputs (output nodes only)  in: This...",""],
["./onedriveout.html","Nodes &#62; Output &#62; OneDrive Out","Purpose  To upload content to Microsoft OneDrive cloud service.  Inputs (output nodes only)  in: Files to be uploaded.  Output...",""],
["./output-nodes.html","Main menu &#62; Nodes (menu) &#62; Output","Specialized  nodes for final delivery. Typically to pack several files into a standard package and to automate final delivery to cloud server...",""],
["./output.html","Nodes &#62; Output","Output Navigation: Nodes Output ",""],
["./panasonic8kp2.html","Nodes &#62; Tasks &#62; Panasonic8KP2","Purpose  This task node permits to transcode to Panasonic8k P2 media (Megapack). This format is made as a collection of multiple media files ...",""],
["./panasonic8kp2pack.html","Nodes &#62; Input &#62; Panasonic8KP2 Pack","Purpose  The Panasonic P28kPack input node permits to load Panasonic 8KP2 media (Megapack) or set the content of a folder or watcher node as ...",""],
["./panasonicavcintra.html","Nodes &#62; Tasks &#62; Panasonic AVC intra","Purpose  The .mxf media files in Panasonic AVC intra format.  Outputs  AV Out: The rendered media files.  Standard properties ...",""],
["./panasonicp2pack.html","Nodes &#62; Input &#62; Panasonic P2 Pack","Purpose  The Panasonic P2 Pack node permits to load Panasonic P2 media (Megapack) or set the content of a folder or watcher node as Panasonic...",""],
["./phantomfile.html","Nodes &#62; Input &#62; Phantom File","Purpose  This node will load Phantom camera files and set their properties before passing them to other nodes.  Outputs  AV Out: A ...",""],
["./pix.html","Nodes &#62; Output &#62; Pix","Purpose  Upload content to a Pix.online Platform account. Note: In order to ensure full compatibility of your file with the Pix platform, it ...",""],
["./pixcompliantfile.html","Nodes &#62; Tasks &#62; Pix Compilant File","Purpose  Create a compatible .mp4 file ready to upload to the Pix platform. Inputs  AV In: The image track to be encoded.  Ext. Aud...",""],
["./pixcompliantfile_2.html","Nodes &#62; Tasks &#62; PixellAI","Purpose  Deep learning-based video quality enhancer using the cloud service Pixell AI, from 4by4.    This node will upload input vi...",""],
["./png.html","Nodes &#62; Tasks &#62; Png","Purpose  To create a .png file or a .png  enumerated sequence of files These .png files can include alpha channel or not depending on th...",""],
["./preferences-.html","Main menu &#62; Preferences ","In this window, only the basic settings are shown by default. The down arrow icon in the upper right corner permits to show additional options.",""],
["./project-manager-window.html","Mistika Workflows Interface &#62; A first workflow example","A basic workflow is going to be explained for demonstration purposes. In this case, we are going to transcode a TIFF sequence into a ProRes movie ...",""],
["./prores.html","Nodes &#62; Tasks &#62; ProRes","Purpose  Create .mov media files in Apple ProRes format Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The a...",""],
["./psd.html","Nodes &#62; Tasks &#62; Psd","Purpose  To create a .PSD file or a .PSD  enumerated sequence of files. These .PSD files can include alpha channel or not depending on t...",""],
["./pulsar.html","Nodes &#62; Tasks &#62; Pulsar","Purpose  This node allows the automation of posting jobs to the QC tool Pulsar, from Veneratech, while applying the desired QC template avail...",""],
["./pydonothing.html","Nodes &#62; Tasks &#62; pyDoNothing","Purpose  A very basic Python example. This example creates a simple task node with one input and one output.  Inputs  Input: Any ki...",""],
["./pyglobalconfig.html","Nodes &#62; Tasks &#62; pyGlobalConfig","Purpose  A Python node example, about how to create a couple of properties that can then be accessed from a different workflow.  Inputs ...",""],
["./pyhelloworld.html","Nodes &#62; Tasks &#62; pyHelloWorld","Purpose  A very basic Python example to just print  \"hello world\"  in the Script Editor console. This example creates a s...",""],
["./pyprintinputs.html","Nodes &#62; Output &#62; pyPrintInputs","Purpose  A Python node example that will print all  the metadata received by the input connector (universal paths) in the Script Editor ...",""],
["./python-scripting-tools-in-mist.html","Python scripting tools","Python scripting tools Navigation: No topics above this level Python scripting tools ",""],
["./python.html","Nodes &#62; Tasks &#62; Python","Purpose  A  Python node with just the basic functions, to be used as the most basic template for creating python nodes.  This is ju...",""],
["./quickprototype.html","Nodes &#62; Tasks &#62; quickPrototype","Purpose  A  Python node with definable connectors, to be used as a template for creating python nodes.  Inputs  Any number of ...",""],
["./raffile.html","Nodes &#62; Input &#62; RAF File","Purpose  This node will load Fuji RAF files and set their properties before passing them to other nodes. Custom debayer options are supported...",""],
["./redfile.html","Nodes &#62; Input &#62; Red File","Purpose  This node will load RED r3d files and set their properties before passing them to other nodes. Custom debayer options are supported....",""],
["./rgblevels.html","Nodes &#62; Tasks &#62; RGB Levels","Purpose  Convert between Data Levels and Video Levels (both directions are possible)  That is what some people (wrongly) call \"full...",""],
["./rndfile.html","Nodes &#62; Input &#62; Rnd File","Purpose  This node will load a .rnd file (Mistika render script) and set its properties before passing it to other nodes, such as the Mistika...",""],
["./s3in.html","Nodes &#62; Input &#62; s3In","Purpose  This node allows you to download files from a S3 bucket from Amazon AWS  Outputs   Out: To pass downloaded files to other ...",""],
["./s3out.html","Nodes &#62; Output &#62; s3Out","Purpose  This node allows you to upload files to a S3 bucket (Amazon AWS)  Inputs  In: Files to upload  Outputs  Out: To ...",""],
["./serializeinputs.html","Nodes &#62; Tasks &#62; Serialize inputs","Purpose  This node is used to join different inputs into the same task or output node. Equivalent to creating multiple copies of the node at ...",""],
["./setdisplayfilterfiles.html","Nodes &#62; Tasks &#62; Set DisplayFilter files","Purpose  Given a display filter that was created containing certain images, this node permits to substitute those images by others. This perm...",""],
["./setupmetadata.html","Nodes &#62; Tasks &#62; Set UP Metadata","Purpose  Overwrite the metadata of the incoming file (its Universal Path) with the metadata from another one.  Inputs  in: media fi...",""],
["./seven7th.html","Nodes &#62; Tasks &#62; Seven7th","Purpose  Create .sth media files in 7thsense format Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The audio...",""],
["./shotgridcreate.html","Nodes &#62; Tasks &#62; ShotGrid Create","Purpose  This node connects to a Shotgrid database and allows the creation of Shotgrid’s entities based on any kind of input files: Project, ...",""],
["./shotgridcsvreader.html","Nodes &#62; Tasks &#62; ShotGrid CSV Reader","Purpose  The ShotGrid CSV Read node is intended to locate the last version of each shot in a typical VFX project folder structure at any stor...",""],
["./signiant.html","Nodes &#62; Output &#62; Signiant","Purpose  File transfer through the Signiant platform.  Inputs  File: The file to be transferred.   Standard properties Object ...",""],
["./skyadi.html","Nodes &#62; Tasks &#62; SkyADI","Purpose  This node creates an XML file in ADI v1.1 / Cablelabs Content 1.1 format (or ADIv3 / Cablelabs Content 3.0 in the case of SkyADI). &#38;...",""],
["./slack.html","Nodes &#62; Output &#62; Slack","Purpose  Send messages with media content to Slack platform. Inputs  File: The media file ready to upload.  Standard properties Obj...",""],
["./slack_(1).html","Slack","Purpose  Send messages with media content through Slack. Inputs  File: The media file ready to upload.  Standard properties Object ...",""],
["./sonyfile.html","Nodes &#62; Input &#62; Sony File","Purpose  This is the node that allows you to enter Sony RAW files and control their properties for use within the Workflow.  Outputs &#38;nb...",""],
["./sonyxdrootpack.html","Nodes &#62; Input &#62; Sony XDROOT Pack","Purpose  The Sony XDROOT Pack node permits to load Sony XDROOT media (Megapack) or set the content of a folder or watcher node as Sony XDROOT...",""],
["./splitmovie.html","Nodes &#62; Tasks &#62; Split Movie","Purpose  To split a movie file into different clips with definable duration (number of frames). The result will be multiple clips using the n...",""],
["./stichautocalibrate.html","Nodes &#62; Tasks &#62; Stitch Auto Calibrate","Purpose  To apply automatic calibration of the lenses of an VR rig before stitching the cameras, in order to automate VR production. This nod...",""],
["./stitchalignmesh.html","Nodes &#62; Tasks &#62; Stitch Align Mesh","Purpose  To apply automatic image warping to remove Stereo3D vertical disparities, in order to automate VR stereo3D production.  Equival...",""],
["./stitchrefiner.html","Nodes &#62; Tasks &#62; Stitch Refiner","Purpose  To apply automatic adjustments for VR stitching, in order to automate VR production. This node will get a Mistika  .rnd  f...",""],
["./stmap.html","Nodes &#62; Tasks &#62; STMap","Purpose  To apply an STmap to Input images. The images are adjusted to the STmap shape. Inputs  Image: Files to be processed.  STma...",""],
["./system-integration.html","Python scripting tools &#62; System integration","Introduction  The main system integration resource is the integrated Python engine, which is covered in its own  chapters Python scripti...",""],
["./tagcolorspace.html","Nodes &#62; Tasks &#62; Tag Color Space","Purpose   To declare the color space settings (gamma &#38; gamut) for incoming files not having this information, then passing them to the ou...",""],
["./tagcolorspace_2.html","Nodes &#62; Tasks &#62; Tag Pixel Aspect Ratio","Purpose   To declare the pixel aspect ratio standard used by incoming files, then passing them  to the output connector alongside with t...",""],
["./tagfps.html","Nodes &#62; Tasks &#62; Tag FPS","Purpose  To declare the FPS (Frames Per Second) for the incoming files, then passing them to the output connector alongside with the new FPS ...",""],
["./tar.html","Nodes &#62; Output &#62; Tar","Purpose  Store files and folders in a single .tar file.  Inputs  File: The file or folder with the content to include in the .tar f...",""],
["./tasks.html","Nodes &#62; Tasks","Tasks Navigation: Nodes Tasks ",""],
["./tiff.html","Nodes &#62; Tasks &#62; Tiff","Purpose  To create a .tif file or a .tif enumerated sequence of files. These .tif files can include alpha channel or not, depending on the se...",""],
["./topaz.html","Nodes &#62; Tasks &#62; Topaz","Purpose  To automate usage of the Topaz Video AI software for AI video enhancement (AI based scaling, denoise, de-blur, slow motion, compress...",""],
["./trash.html","Nodes &#62; Tasks &#62; Trash","Purpose  This node delete all the files related to the Universal Paths specified in the inputs.   Note that this is not limited to indep...",""],
["./unicolor.html","Nodes &#62; Tasks &#62; Unicolor","Purpose  To convert between color spaces in non destructive manner. As a difference to color transformations based on LUT3D (which are not fu...",""],
["./uvp.html","Nodes &#62; Output &#62; UVP","Purpose  This node generates specific metadata files for the \"Universal OVD Package\" content. The metadata can be generated by othe...",""],
["./vimeo.html","Nodes &#62; Output &#62; Vimeo","Purpose  Upload videos to Vimeo platform.   Inputs  in: The video file to be upload.  Outputs  out: The video file that w...",""],
["./vodafoneespxml.html","Nodes &#62; Tasks &#62; Vodafone Esp","Purpose  This node creates delivery packages to the specifications of Vodafone España (which uses its own XML specifications).  The deli...",""],
["./vrinputbunches.html","Nodes &#62; Tasks &#62; VR Input Bunches","Purpose  This node automates the stitching from VR camera rigs, that is, camera rigs with multiple cameras (overlapped field of view).  ...",""],
["./watcher.html","Nodes &#62; Input &#62; Watcher","Purpose  This is one of the most important nodes. The Watcher node is useful to automate triggering workflows execution. Use this node to sta...",""],
["./watermarkcfg.html","Nodes &#62; Tasks &#62; WatermarkCfg","Purpose  To configure user text for the Watermark display filter,  providing properties to type your own (head, body, and footer), which...",""],
["./wav.html","Nodes &#62; Tasks &#62; WAV","Purpose  To create .wav  audio  Inputs  input: A media file with audio  Outputs  wav: A .wav file    Stand...",""],
["./whatsapp.html","Nodes &#62; Output &#62; WhatsApp","Purpose  This node is used to send WhatsApp notifications. Note: Before using this node you will need to have a Meta Developers Account and g...",""],
["./window-tabs.html","Main menu","Main menu Navigation: No topics above this level Main menu ",""],
["./window.html","Main menu &#62; Window","The window menu is focused on organizing the interface at your will. This permits to create a different GUI layout for each type of user.",""],
["./winsmbcopy.html","Nodes &#62; Tasks &#62; WinSMBCopy","Purpose  Copy or Move files to a network drives using SMB protocol ( accepting mount credentials and supporting the SMB/CIFS  path synta...",""],
["./wmv.html","Nodes &#62; Tasks &#62; WMV","Purpose  To create WMV files (Windows Media Video)  Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): The ...",""],
["./workflows-window.html","Main menu &#62; Workflows ","The Workflows menu contains the following features:",""],
["./xavc.html","Nodes &#62; Tasks &#62; XAVC","Purpose  Create  .mxf media files in XAVC format.  Inputs  AV In: The image track to be encoded.  Ext. Audio (Optional): ...",""],
["./xdcam.html","Nodes &#62; Tasks &#62; XDCAM","Purpose  The XDCAM task node permits to transcode to XDCAM media (Megapack)  Inputs  AV In: The image track to be encoded.  Ex...",""],
["./xlsxtocsv.html","Nodes &#62; Tasks &#62; XLSX to CSV","Purpose  Convert files from XLSX (Microsoft Excel format) to .csv format.    Inputs  xlsx: Input files in  XLSX format &#38;n...",""],
["./xmltoxlsx.html","Nodes &#62; Tasks &#62; XMLtoXLSX","Purpose  Convert XML files to XLSX (Microsoft Excel format)    Inputs  xml: The XML file to be converted  Outputs  x...",""],
["./youleanloudnessmeter.html","Nodes &#62; Tasks &#62; Youlean Loudness Meter","Purpose  This node allows the automation of analysis, report, and normalize audio files based on the desired presets, channel configuration, ...",""],
["./youtube.html","Nodes &#62; Output &#62; Youtube","Purpose  Upload videos to YouTube platform.  Before you can use this node you will need to get some credentials from Google. It only nee...",""]];
